version: '3.9'
services:
  sample-app:
    build:
      context: .
    restart: on-failure
    environment:
      DEBUG: "*"
      AWS_REGION: "eu-central-1"
      AWS_CONTAINER_CREDENTIALS_FULL_URI:
      AWS_CONTAINER_AUTHORIZATION_TOKEN:
    network_mode: host    
